In [2]:
import torch
import torch.nn as nn

class network(nn.Module):
    
    def __init__(self):
        super().__init__()
        self.main = torch.nn.Sequential(
            nn.Linear(100, 100),
            nn.BatchNorm1d(100),
            nn.Linear(100,1),
            nn.Sigmoid()
        )
        
    def forward(self, inp):
#         for layer in self.main:
#             inp = layer(inp)
        print('forward')
        return self.main(inp)



In [5]:
from multiprocessing import Pool
# import torch.multiprocessing as mp
ref_net = network()
def f(x):
    net = network()
    net.load_state_dict(ref_net.state_dict())
    print('setup')
#     with torch.no_grad():
#         print(next(net.parameters()))
    out = net(x)
    print('output')
    return out.detach()

a = list(torch.randn(5,2,100))
# for i in range(2):
with Pool(5) as p:
    print(p.map(f, a))
fcn = torch.nn.Sequential(
            nn.Linear(100, 100),
            nn.BatchNorm1d(100),
            nn.Linear(100,1),
            nn.Sigmoid()
        )
b = fcn(torch.randn(2,100))
with Pool(5) as p:
    print(p.map(f, a))

with Pool(5) as p:
    print(p.map(f, a))

with Pool(5) as p:
    print(p.map(f, a))


setupsetupsetup
setup

setupforwardforward


forwardforward
forward


output
output
output
output
output
[tensor([[0.4567],
        [0.5829]]), tensor([[0.3078],
        [0.7254]]), tensor([[0.3757],
        [0.6612]]), tensor([[0.4358],
        [0.6033]]), tensor([[0.4414],
        [0.5979]])]
setupsetupsetup

setupforwardsetup
forward

forward

forward
forward



Process ForkPoolWorker-36:
Process ForkPoolWorker-40:
Process ForkPoolWorker-39:
Process ForkPoolWorker-38:
Process ForkPoolWorker-37:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._t

KeyboardInterrupt: 

In [ ]:
import torch 
from torch import multiprocessing,nn 
 
output_size = 13 
input_dim = output_size 
hidden_dim = 128 
layer_dim = 1 
 
lstm = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, num_layers=layer_dim, batch_first=True) 
torch.save(lstm.state_dict(),"plain.pt") 
 
def run(state): 
    model = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, num_layers=layer_dim, batch_first=True) 
    model.load_state_dict(torch.load("plain.pt")) 
    x=model(state) 
    return x 
 
state=torch.rand(1,10,13) 
threads=[] 
for i in range(1): 
    p = multiprocessing.Process(target=run,args=(state,)) 
    threads.append(p) 
for i in threads: 
    i.start() 
for i in threads: 
    i.join() 
print("CHECKPOINT One") 
# run(state) 
fcn = torch.nn.Sequential(
            nn.Linear(100, 100),
            nn.BatchNorm1d(100),
            nn.Linear(100,1),
            nn.Sigmoid()
        )
a = fcn(torch.randn(2,100))
print("CHECKPOINT Two")
threads=[] 
for i in range(1): 
    p = multiprocessing.Process(target=run,args=(state,)) 
    threads.append(p) 
for i in threads: 
    i.start() 
for i in threads: 
    i.join()
print("CHECKPOINT Three")

CHECKPOINT One
CHECKPOINT Two


In [ ]:

from setting import TASK

if TASK == 'antenna_selection':
    from antenna_selection.observation import Observation, LinearObservation
    from antenna_selection.as_bb_test import ASBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_cast_beamforming':
    from single_beamforming.observation import Observation, LinearObservation
    from single_beamforming.acr_bb import ACRBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_group_as_bm':
    from single_group_as_bm.observation import Observation, LinearObservation
    from single_group_as_bm.bb import BBenv as Environment, DefaultBranchingPolicy, solve_bb

import torch
import torch.nn as nn
import numpy as np

from gnn_policy import GNNPolicy, GNNNodeSelectionPolicy
from tqdm import tqdm
import torch_geometric
import gzip
import pickle
from gnn_dataset import GraphNodeDataset, instance_generator
from pathlib import Path
from gnn_dataset import get_graph_from_obs
import shutil
import time
import os
from torch.multiprocessing import Pool
import torch.multiprocessing as mp


from models.fcn_policy import FCNNodeSelectionLinearPolicy, FCNNodeDataset
from torch.utils.data import DataLoader
from testH import Channels

from torch.utils.data import Dataset

MAX_STEPS = 10000

class OracleDataset(Dataset):
    def __init__(self, root=None, sample_files=None):
        self.sample_files = sample_files
        self.file_index = len(self.sample_files)
        self.root = root

    def len(self):
        return len(self.sample_files)

    def get(self, index):
        with gzip.open(self.sample_files[index], 'rb') as f:
            sample = pickle.load(f)
            # Sample expected of format H, solution, objective, timesteps, time
            return sample

    def put(self, sample):
        with gzip.open(os.path.join(root, 'sample_{}.pkl'.format{self.file_index}), 'wb') as f:
            pickle.dump(sample, f)


class DataCollect(object):
    def __init__(self, observation_function=Observation, max_ant=None, policy='oracle',filepath=None, policy_type='gnn', oracle_solution_filepath=os.path.join(DATA_PATH)):
        # env = Environment(observation_function=observation_function, epsilon=0.002)
        self.observation_function = observation_function
        self.max_ant = max_ant
        self.filepath = filepath
        self.branching_policy = DefaultBranchingPolicy()
        self.policy_type = policy_type
        self.node_select_policy = None
        self.oracle_problem_index = 0
        self.oracle_dataset = OracleDataset(root=oracle_solution_filepath)

    def load_oracle_data(self):
        if self.oracle_solution_filepath is not None:
            oracle_files = [str(path) for path in Path(self.oracle_solution_filepath).glob('*.pkl')]
            with  

    def save_oracle_data(self):
        if self.oracle_solution_filepath is not None:


    def get_instances

    def collect_data(self, instance_gen, num_instances=10, policy='oracle'):

        N, M = next(instance_gen).shape[1], next(instance_gen).shape[2]
        H = np.random.randn(num_instances, N, M) + 1j*np.random.randn(num_instances, N,M)   
        # H = Channels.copy() 
        instances = np.stack((np.real(H), np.imag(H)), axis=1)
        

        arguments_oracle = list(zip(list(instances), [self.max_ant]*num_instances))
        print('starting first pool')
        with Pool(min(num_instances, 30)) as p:
            out_oracle = p.map(self.solve_bb_process, arguments_oracle)
            print('first pool ended')

        # the returned order is x_opt:[can be a tuple], global_U, timsteps, time
        optimal_solution_list = [out_oracle[i][0] for i in range(len(out_oracle))]
        optimal_objective_list = [out_oracle[i][1] for i in range(len(out_oracle))]
        avg_oracle_steps = np.mean(np.array([out_oracle[i][2] for i in range(len(out_oracle))]))
        avg_oracle_time = np.mean(np.array([out_oracle[i][3] for i in range(len(out_oracle))]))

        arguments_ml = list(zip(list(instances), optimal_solution_list, optimal_objective_list, range(num_instances), [policy]*num_instances))
        # arguments_ml = list(zip(list(instances), optimal_solution_list, optimal_objective_list, range(num_instances)))

        print('starting second pool')
        with Pool(min(num_instances,30)) as p:
            out_ml = p.map(self.collect_data_instance, arguments_ml)
            # out_ml = p.map(self.dummy_collect_instance, arguments_ml)

            print('second pool ended')
        
        # the returned order for collect_data_instance is ()
        avg_ml_time = np.mean(np.array([out_ml[i][0] for i in range(len(out_ml))]))

        avg_ml_ogap = 0
        num_solved = 0
        for i in range(len(out_ml)):
            if out_ml[i][1] > -1:
                avg_ml_ogap += out_ml[i][1] 
                num_solved += 1
        avg_ml_ogap /= num_solved
        # avg_ml_ogap = np.mean(np.array([out_ml[i][1] for i in range(len(out_ml))]))
        avg_ml_steps = np.mean(np.array([out_ml[i][2] for i in range(len(out_ml))]))

        return avg_oracle_time/avg_ml_time, avg_ml_ogap, avg_oracle_steps/avg_ml_steps
        # return 0, 0, 0

    def collect_data_instance(self, arguments):
        instance, w_optimal, optimal_objective, file_count, policy_filepath = arguments
        print('function {} started'.format(file_count))
        #TODO: do the following with parameters not filename
        # print('optimal ', w_optimal)
        env = Environment(observation_function=self.observation_function, epsilon=0.002)
        env.set_node_select_policy(node_select_policy_path=policy_filepath, policy_type=self.policy_type)
        
        env.reset(instance, max_ant=self.max_ant,  oracle_opt=w_optimal)
        branching_policy = DefaultBranchingPolicy()
        t1 = time.time()
        timestep = 0
        done = False
        time_taken = 0
        sum_label = 0
        node_counter = 0
        while timestep < MAX_STEPS and len(env.nodes)>0 and not done: 
            # print('timestep {}'.format(timestep))
            env.fathom_nodes()
            if len(env.nodes) == 0:
                break
            node_id, node_feats, label = env.select_node()
            if len(env.nodes) == 0:
                break
            time_taken += time.time()-t1
            sum_label += label
            self.save_file((node_feats, label), file_count, node_counter)
            node_counter += 1
            t1 = time.time()

            # print('Node id for pruning decision {}'.format(env.nodes[node_id].node_index))
            prune_node = env.prune(node_feats)
            # prune_node = False
            if prune_node:
                env.delete_node(node_id)
                continue
            else:
                # print('Node id {}'.format(env.nodes[node_id].node_index))
                last_id = len(env.nodes)

                branching_var = branching_policy.select_variable(node_feats, env.action_set_indices)
                try:
                    done = env.push_children(branching_var, node_id)
                except:
                    break
                
                # for i in range(last_id, len(env.nodes)):
                #     print('Children {} z_mask {}, z_sol {}, l_angle {}, u angle {}'.format(env.nodes[i].node_index, env.nodes[i].z_mask, env.nodes[i].z_sol, env.nodes[i].l_angle, env.nodes[i].u_angle) )

                # print('*********')
                # print()
            timestep = timestep+1
            if env.is_terminal():
                break

        if node_counter < 1:
            print('node counter null H {}, w_opt {}'.format(env.H_complex, w_optimal))
        # ml = np.linalg.norm(env.W_incumbent, 'fro')**2
        ml = env.global_U
        ogap = ((ml - optimal_objective)/optimal_objective)*100
        time_taken += time.time() - t1
        print('instance result', timestep, ogap, time_taken, sum_label, optimal_objective, ml)
        return timestep, ogap, time_taken, sum_label/node_counter
    
    def solve_bb_process(self, tup):
        instance, max_ant = tup
        return solve_bb(instance, max_ant)     

    def save_file(self, sample, file_count, node_counter):
        if self.filepath is not None:
            filename = self.filepath + f'sample_{file_count}_{node_counter}.pkl'
            with gzip.filename, 'wb') as f:
                pickle.dump(sample, f)

    def dummy_collect_instance(self, arguments):
        instance, w_optimal, optimal_objective, file_count = arguments
        print('started collect instance {}'.format(file_count))
        import time
        time.sleep(1)
        print('ended collect instance {}'.format(file_count))

In [1]:
a = iter([12,23,4,5])

In [7]:
next(a)

StopIteration: 

In [8]:

import torch
import torch.nn as nn
import numpy as np

from gnn_policy import GNNPolicy, GNNNodeSelectionPolicy
from tqdm import tqdm
import torch_geometric
import gzip
import pickle
from gnn_dataset import GraphNodeDataset, instance_generator
from pathlib import Path
from gnn_dataset import get_graph_from_obs
import shutil
import time
import os
from torch.multiprocessing import Pool
import torch.multiprocessing as mp


from models.fcn_policy import FCNNodeSelectionLinearPolicy, FCNNodeDataset
from torch.utils.data import DataLoader
from testH import Channels

from torch.utils.data import Dataset

class Test(Dataset):
    def __init__(self, root=None):
        pass
    
    def __len__(self):
        return 50

    def __getitem__(self, index):
        return torch.randn(5), torch.randn(2)



In [9]:
tset = Test()

In [28]:
tlist = [tset[i] for i in range(5)]

In [29]:
tlist

[(tensor([-0.8494,  1.2864,  1.6810,  0.0406, -0.6355]),
  tensor([-0.4165,  1.5088])),
 (tensor([ 0.1141, -0.0931, -0.3955,  0.3493, -0.8011]),
  tensor([-1.3970, -0.2589])),
 (tensor([ 0.5047,  0.5620, -0.8691,  0.3053, -0.5327]),
  tensor([-0.6744, -1.7742])),
 (tensor([-1.4625,  2.2586,  0.7961,  0.5730,  0.0742]),
  tensor([0.0974, 0.5520])),
 (tensor([-0.0116,  1.4583, -0.7173,  0.1428,  0.4294]),
  tensor([ 1.2506, -1.4425]))]

In [32]:
list(zip(*tlist))

[(tensor([-0.8494,  1.2864,  1.6810,  0.0406, -0.6355]),
  tensor([ 0.1141, -0.0931, -0.3955,  0.3493, -0.8011]),
  tensor([ 0.5047,  0.5620, -0.8691,  0.3053, -0.5327]),
  tensor([-1.4625,  2.2586,  0.7961,  0.5730,  0.0742]),
  tensor([-0.0116,  1.4583, -0.7173,  0.1428,  0.4294])),
 (tensor([-0.4165,  1.5088]),
  tensor([-1.3970, -0.2589]),
  tensor([-0.6744, -1.7742]),
  tensor([0.0974, 0.5520]),
  tensor([ 1.2506, -1.4425]))]

In [2]:
debug_dict

{'H': array([[-0.05166506+1.30178603j, -0.47204338+1.57627116j,
         -2.49365647+1.18535672j, -0.40341769-0.5644057j ,
          1.69701885+1.26713744j, -0.43372622+0.17093886j,
          1.0915912 -0.71028303j, -0.72920396+0.64180858j,
          0.86271614+1.00365057j, -0.3919123 -0.01821218j,
          0.38093252-1.01793452j, -0.68168604-0.26129524j],
        [-0.0301732 +0.48022213j, -1.49603328-1.8474315j ,
          0.14215553-0.01177327j,  1.2166248 -1.12422897j,
         -0.24373051+0.62189381j, -1.63963864+0.52988676j,
         -0.97124165+1.46506723j, -0.42911891+0.96023565j,
         -0.80415789+0.74347491j, -0.59576659+0.58869069j,
         -1.51656786+2.77555281j, -0.90122438+1.04097306j],
        [ 0.70291538-0.23428069j,  0.7685298 -1.65853699j,
         -1.17274081+0.62189951j,  0.77379751-1.30863758j,
         -0.68758407+0.94034472j,  0.96191735-0.45152773j,
         -1.01692934+0.98029305j, -0.79750341-0.08734199j,
         -1.0381392 -0.40981663j, -0.01886287-0.3

In [ ]:
 w = [-0.08073542-0.38585263j -0.92626801-0.16917217j  0.        +0.j
  0.        +0.j          0.        +0.j          0.        +0.j        ]

In [3]:
from numpy import array
import numpy as np
import pickle
with open('debug.pkl', 'rb') as f:
    debug_dict = pickle.load(f)

H = debug_dict['H']
z_opt, w_opt = debug_dict['w_opt']
obj_opt = debug_dict['obj']
ml = debug_dict['ml']

    

# H = array([[ 3.74044040e-01-0.22984038j,  3.50558309e-01-1.20423216j,
#       -1.41668213e-01+1.04179693j,],
#      [ 1.34190298e-03-0.04118129j, -3.75233329e-01-0.23039803j,
#       -1.11547412e+00-0.68094106j,],
#      [ 6.77504534e-01-0.05547548j, -2.07440535e+00+1.14051609j,
#       -9.16197678e-02+1.61068477j,],
#      [ 4.63684159e-01-0.21816427j, -1.12971446e+00-1.09075708j,
#        1.33494810e+00+0.62227851j,]] )
# instance = np.stack((np.real(H), np.imag(H)), axis=0)
# z_opt = array([1., 0., 1., 1.])

# w_opt = array([0.40771115-0.25052794j, 0.        +0.j        ,
#        0.73848564-0.06046874j, 0.50541963-0.23780089j])
from dagger_collect_data_multiprocess import DataCollect
from setting import TASK

if TASK == 'antenna_selection':
    from antenna_selection.observation import Observation, LinearObservation
    from antenna_selection.as_bb_test import ASBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_cast_beamforming':
    from single_beamforming.observation import Observation, LinearObservation
    from single_beamforming.acr_bb import ACRBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_group_as_bm':
    from single_group_as_bm.observation import Observation, LinearObservation
    from single_group_as_bm.bb import BBenv as Environment, DefaultBranchingPolicy, solve_bb

import torch
import torch.nn as nn
import numpy as np

from gnn_policy import GNNPolicy, GNNNodeSelectionPolicy
from tqdm import tqdm
import torch_geometric
import gzip
import pickle
from gnn_dataset import GraphNodeDataset, instance_generator
from pathlib import Path
from gnn_dataset import get_graph_from_obs
import shutil
import time
import os
from torch.multiprocessing import Pool
import torch.multiprocessing as mp


from models.fcn_policy import FCNNodeSelectionLinearPolicy, FCNNodeDataset
from torch.utils.data import DataLoader
from testH import Channels
MAX_STEPS = 10000

from torch.utils.data import Dataset

data_collect = DataCollect( 
                observation_function=Observation,
                max_ant=2, 
                policy='oracle',
                train_filepath='data/dummy_path', 
                policy_type='gnn', 
                oracle_solution_filepath='data/dummy_path',
                num_instances=10)

data_collect.collect_data_instance((np.stack((np.real(H), np.imag(H)), axis=0), (z_opt, w_opt), obj_opt, 0, 'oracle'))

********in Datacollect 2
function 0 started
id: 0 oracle z: [ 1.  1.  0.  0. -0.  0.], oracle_angle: [0.         4.87860629 3.20348637 3.14159265 4.57231126 1.87194671
 5.04181205 0.66559575 4.33199676 3.01072384 1.68276101 3.14933188], node mask: [0. 0. 0. 0. 0. 0.],  node z: [0.33334335 0.33333257 0.33332962 0.33333426 0.33333034 0.33332987], node angle: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], [6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531 6.28318531]
optimal node depth is 1
-- This node is optimal

expanding node id 0, children (array([0., 0., 0., 0., 0., 0.]), array([0.33334335, 0.33333257, 0.33332962, 0.33333426, 0.33333034,
       0.33332987]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([6.28318531, 6.28318531, 6.28318531, 6.28318531, 6.28318531,
       6.28318531, 6.28318531, 6.28318531, 6.28318531, 6.28318531,
       6.28318531, 6.28318531]))

 creating children ((array([0., 0., 1., 0

theta [0.         3.34709898 6.15015936 4.9113327  1.71814084 3.54444343
 6.18139772 2.9578783  3.48972588 2.43895053 2.54824818 2.33204847]
True

 creating children ((array([1., 0., 1., 0., 1., 0.]), array([ 1.        ,  0.50024425, -0.        ,  0.49876714, -0.        ,
        0.4957648 ])), (array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.57079633,
       0.        , 0.        ]), array([6.28318531, 6.28318531, 6.28318531, 3.14159265, 6.28318531,
       6.28318531, 6.28318531, 6.28318531, 6.28318531, 3.14159265,
       6.28318531, 6.28318531])))
z True
theta [0.         4.02339732 0.10835421 0.48534213 2.34564782 1.92878742
 5.31515542 0.58775235 3.98958464 2.54450911 1.56361183 2.70929036]
True
theta [0.         4.41878791 2.38334148 1.85321979 4.10927414 1.44898644
 4.53512813 0.45290721 4.278307   2.59665324 1.22532744 2.77322309]
True

 creating children ((array([1., 0., 1., 0., 1., 0.]), array([ 1.    

id: 17 oracle z: [ 1.  1.  0.  0. -0.  0.], oracle_angle: [0.         4.87860629 3.20348637 3.14159265 4.57231126 1.87194671
 5.04181205 0.66559575 4.33199676 3.01072384 1.68276101 3.14933188], node mask: [1. 0. 1. 0. 1. 1.],  node z: [ 1.          0.50282611 -0.          0.49717389 -0.          0.        ], node angle: [0.         0.         0.         3.14159265 0.         0.
 0.         0.         0.         1.57079633 0.         0.        ], [6.28318531 6.28318531 6.28318531 4.71238898 6.28318531 6.28318531
 6.28318531 6.28318531 6.28318531 3.14159265 6.28318531 6.28318531]
optimal node depth is 5
-- This node is optimal

expanding node id 17, children (array([1., 0., 1., 0., 1., 1.]), array([ 1.        ,  0.50282611, -0.        ,  0.49717389, -0.        ,
        0.        ]), array([0.        , 0.        , 0.        , 3.14159265, 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.57079633,
       0.        , 0.        ]), array([6.28318531, 6.28318531, 6.2831853


 creating children ((array([1., 1., 1., 1., 1., 1.]), array([ 1.,  1., -0.,  0., -0.,  0.])), (array([0.        , 0.        , 0.        , 3.53429174, 3.14159265,
       0.        , 0.        , 0.        , 0.        , 1.57079633,
       0.        , 0.        ]), array([6.28318531, 6.28318531, 6.28318531, 3.92699082, 6.28318531,
       6.28318531, 6.28318531, 6.28318531, 6.28318531, 3.14159265,
       6.28318531, 6.28318531])))
theta [-4.10019272e-06  5.04760532e+00  3.47560101e+00  3.46783549e+00
  4.77546258e+00  1.92084545e+00  5.20406835e+00  7.90557744e-01
  4.46161835e+00  3.18952300e+00  1.77618365e+00  3.26997517e+00]
False
antennas: None not optimal, may be infeasible
id: 22 oracle z: [ 1.  1.  0.  0. -0.  0.], oracle_angle: [0.         4.87860629 3.20348637 3.14159265 4.57231126 1.87194671
 5.04181205 0.66559575 4.33199676 3.01072384 1.68276101 3.14933188], node mask: [1. 1. 1. 1. 1. 1.],  node z: [ 1.  1. -0.  0. -0.  0.], node angle: [0.         0.         3.14159265 1.57079


 creating children ((array([1., 1., 1., 1., 1., 1.]), array([ 1.,  1., -0.,  0., -0.,  0.])), (array([0.        , 0.        , 3.33794219, 3.14159265, 3.14159265,
       0.        , 0.        , 0.        , 0.        , 1.57079633,
       0.        , 0.        ]), array([6.28318531, 6.28318531, 3.53429174, 3.53429174, 6.28318531,
       6.28318531, 6.28318531, 6.28318531, 6.28318531, 3.14159265,
       6.28318531, 6.28318531])))
theta [0.         5.00517199 3.39563078 3.38112723 4.71868922 1.92751188
 5.16619198 0.75753517 4.42213232 3.14159265 1.76594321 3.24456061]
True
id: 33 oracle z: [ 1.  1.  0.  0. -0.  0.], oracle_angle: [0.         4.87860629 3.20348637 3.14159265 4.57231126 1.87194671
 5.04181205 0.66559575 4.33199676 3.01072384 1.68276101 3.14933188], node mask: [1. 1. 1. 1. 1. 1.],  node z: [ 1.  1. -0.  0. -0.  0.], node angle: [0.         0.         3.33794219 3.14159265 3.14159265 0.
 0.         0.         0.         1.57079633 0.         0.        ], [6.28318531 6.2831853

(16, -4.1628570777286384, 1.7267208099365234, 0.5714285714285714)

In [4]:
w_ml = [-0.08073542-0.38585263j, -0.92626801-0.16917217j, 0,0,0,0]

In [12]:
np.abs(np.matmul(H.conj().T, w_ml))

array([1.00401516, 1.80860452, 1.        , 1.02146289, 2.3872334 ,
       1.49241448, 1.99740471, 1.48927519, 1.0639241 , 1.33661763,
       1.30356343, 1.22328136])

In [10]:
H.shape

(6, 12)

In [8]:
H

array([[-1.62935414-0.31723469j,  0.84309421+0.12790547j,
        -1.00040928+0.05162129j, -1.82170734+1.06549687j,
         0.21861234+0.96090384j, -1.63516144+1.64458702j,
         1.27411948-0.14423582j, -0.63110182+0.06571875j,
         0.05533576-0.46676306j, -0.29026373+0.31651743j,
        -1.38652288+0.6486674j ,  0.32990122+0.78579221j],
       [-0.6685547 -0.77318806j, -0.39771625-1.6020602j ,
         1.19719856-0.47390175j,  0.95762021-0.93846896j,
         0.03269857-2.56392441j, -0.10169103+0.66671216j,
        -0.71762377-1.52588119j, -1.25147345+0.60759643j,
         0.68486657-0.91174962j,  1.31956887+0.09250149j,
        -0.01239112+0.74423448j,  0.93846896+0.10459017j],
       [-0.37196715+0.66236613j,  1.73455471+0.26918035j,
         1.46308907+0.62128398j, -0.11995532+0.31449943j,
        -0.37125536-1.22727958j, -1.11510963+1.03601636j,
         0.57626993+0.26401535j, -0.43296712-0.75893748j,
        -0.08847545+0.46256399j,  0.96265758+1.06721445j,
         0.9

In [1]:
z: [ 1. -0. -0.  1. -0. -0.]
    
oracle_angle:[2.57975549e-17 1.08334399e-01 3.61319869e+00 5.22305904e+00 4.79851500e+00
              5.06206217e+00 2.82546840e+00 3.65078374e-01 2.93932554e+00 1.24732841e+00
              5.91341465e+00 5.65003169e+00]
    

SyntaxError: invalid syntax (<ipython-input-1-c7e62428a2a9>, line 1)

In [ ]:
 [6.14621567 0.35023826 3.73096322 4.95946861 3.91827016 5.11307133
 5.64231658 1.85345724 3.35191419 1.78927128 5.55975739 5.39769699]

In [3]:
from numpy import array
import numpy as np
z_mask = array([0., 1., 1., 1., 0., 0.])
z_sol = array([ 0.51285502,  0.        , -0.        ,  1.        ,  0.48229948, 0.48709965])
l = array([0.        , 0.        , 3.14159265, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

u = array([6.28318531, 6.28318531, 4.71238898, 6.28318531, 6.28318531,
       6.28318531, 3.14159265, 6.28318531, 6.28318531, 6.28318531,
       6.28318531, 6.28318531])


Ha = np.stack((np.real(H), np.imag(H)), axis=0)

from single_group_as_bm.solve_relaxation import *
a = qp_relaxed(Ha, l=l, u=u, z_mask=z_mask, z_sol=z_sol, max_ant=2, T=1000)



In [4]:
a

(array([3.33336144e-01, 9.38227441e-34, 3.83646674e-34, 1.00000000e+00,
        3.33331212e-01, 3.33332644e-01]),
 array([ 2.09788865e-01+2.37833393e-01j, -1.14881485e-17+2.62788295e-17j,
         1.46587559e-17-1.09082123e-17j,  3.03132236e-01-7.70246698e-02j,
        -6.27164786e-02+5.89997594e-02j,  7.65701940e-02+1.24986498e-01j]),
 0.22729699067409723,
 True)

In [8]:
[ 2.09788839e-01+2.37833395e-01j -3.48748007e-13-4.73803825e-13j
 -6.36452318e-13+2.00756873e-14j  3.03132249e-01-7.70246867e-02j
 -6.27164761e-02+5.89997571e-02j  7.65702010e-02+1.24986494e-01j] 0.22729699069218195 False

(array([0.        , 0.        , 3.14159265, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]),)

AttributeError: 'tuple' object has no attribute 'shape'

In [ ]:
[2.06843940e-17 3.80416698e+00 5.52578675e+00 2.28833435e+00 4.90874455e-01
 4.87426410e+00 5.46282896e+00 5.67190191e+00 5.78971549e+00 5.23022332e+00
 5.48339464e+00 5.23491182e+00]

In [12]:
z_mask = array([0., 0., 0., 1., 1., 1.])
z_sol =  array([0.49732556, 0.50250545, 0.49553603, 0.        , 0.        ,0.        ])
l = np.array([0.        , 0.        , 0.        , 1.57079633, 0.        ,
                0.        , 0.        , 0.        , 0.        , 0.        ,
                3.14159265, 0.        ])

u = np.array([6.28318531, 6.28318531, 6.28318531, 3.14159265, 6.28318531,
                6.28318531, 6.28318531, 6.28318531, 6.28318531, 6.28318531,
                6.28318531, 6.28318531])


Ha = np.stack((np.real(H), np.imag(H)), axis=0)

from single_group_as_bm.solve_relaxation import *
a = qp_relaxed(Ha, l=l, u=u, z_mask=z_mask, z_sol=z_sol, max_ant=2, T=1.9531862499490356)



In [13]:
a

(array([7.02337366e-01, 6.08559638e-01, 6.89102996e-01, 2.88510667e-25,
        3.88561273e-26, 1.00760478e-25]),
 array([ 1.03157188e+00+6.22472029e-01j,  5.70773140e-01+5.05568305e-02j,
         6.19953417e-01+8.77823842e-01j, -8.93353341e-11+6.12349782e-11j,
        -8.12297520e-12+7.84069339e-11j,  9.03348367e-11+6.51815013e-11j]),
 2.9348668750546727,
 True)

In [4]:
check_feasibility(H=Ha, l=l, u=u, w=a[1], z=a[0], T=1000)

z True
theta [6.25133935 4.89044301 3.3162547  3.18171451 4.320178   4.9991525
 1.80328269 4.8116165  0.48679716 1.01770303 6.08573713 2.65687539]
w False


False

In [16]:
w = a[1]
z = a[0]
Hc = Ha[0,::] + 1j*Ha[1,::]
T = 1000
if T is not None:
    theta = np.angle(np.matmul(Hc.conj().T, w))
    z_feasible = (np.abs(np.real(w)) <= T*z + epsilon).all() and (np.abs(np.imag(w)) <= T*z + epsilon).all()
    print('z', z_feasible)
else:
    theta = np.angle(np.matmul(Hc.conj().T, w))
    z_feasible = True
theta[theta<-epsilon] += 2*np.pi
print('theta', theta)
theta_feasible = ((theta + 2*np.pi <= u + epsilon) & (theta + 2*np.pi >= l-epsilon)) | ((theta <= u + epsilon) & (theta >= l - epsilon))
print(theta_feasible)

z True
theta [ 4.12682936e-17  4.90540076e+00  3.28012245e+00  3.14158821e+00
  4.30304310e+00  5.02674059e+00  1.79752749e+00  4.76340138e+00
  3.23962764e-01  1.03904232e+00 -6.66603866e-08  2.74408632e+00]
False


In [20]:
(theta >= l - epsilon)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True])

In [22]:
print(theta <= u+epsilon)
 
print(theta + 2*np.pi >= l-epsilon)

[ True False False False False False False False False False  True False]
[ True  True  True  True  True  True  True  True  True  True  True  True]


In [26]:
((theta + 2*np.pi <= u + epsilon) & (theta + 2*np.pi >= l-epsilon)) | ((theta <= u + epsilon) & (theta >= l - epsilon))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [28]:
np.mod(6-0, 6)

0

In [7]:
a[1]

array([-2.73466359e-03+5.06874261e-01j,  5.31151686e-02+3.38969675e-01j,
        2.53893438e-01-1.59294890e-03j, -1.94109030e-13-3.36169118e-14j,
        8.21124192e-14-3.57027329e-13j,  7.06668781e-15+1.46717438e-13j])

In [8]:
a[0]

array([ 6.73160636e-01,  6.68095525e-01,  6.58743838e-01, -7.46731027e-28,
       -3.00592776e-28,  3.11363558e-27])

In [30]:
def check_feasibility(H=None, l=None, u=None, w=None, z=None, T=None):
    Hc = H[0,::] + 1j*H[1,::]
    if T is not None:
        theta = np.angle(np.matmul(Hc.conj().T, w*z))
        z_feasible = (np.abs(np.real(w)) <= T*z + epsilon).all() and (np.abs(np.imag(w)) <= T*z + epsilon).all()
        print('z', z_feasible)
    else:
        theta = np.angle(np.matmul(Hc.conj().T, w*z))
        z_feasible = True
    theta[theta<-epsilon] += 2*np.pi
    print('theta', theta)
    theta_feasible = ((theta <= u + epsilon).all() and (theta >= l - epsilon).all()) or ((theta + 2*np.pi <= u+epsilon).all() and (theta + 2*np.pi >= l-epsilon).all())
                    
    
    print('w', theta_feasible)
    
    return theta_feasible and z_feasible

(array([ 6.73160636e-01,  6.68095525e-01,  6.58743838e-01, -7.46731027e-28,
        -3.00592776e-28,  3.11363558e-27]),
 array([-2.73466359e-03+5.06874261e-01j,  5.31151686e-02+3.38969675e-01j,
         2.53893438e-01-1.59294890e-03j, -1.94109030e-13-3.36169118e-14j,
         8.21124192e-14-3.57027329e-13j,  7.06668781e-15+1.46717438e-13j]),
 0.4391150723097067,
 True)

In [7]:
cvxpy_relaxed(Ha,l=l,u=u, z_mask=z_mask, z_sol=z_sol, max_ant=2, T=1.9531862499490356)

(array([ 0.66878043,  0.65494959,  0.67626998, -0.        , -0.        ,
        -0.        ]),
 array([ 0.0367108 +0.50279706j, -0.01323099+0.30003108j,
         0.2924038 +0.01132593j, -0.        +0.j        ,
        -0.        +0.j        , -0.        +0.j        ]),
 0.4299745422007044,
 True)

In [ ]:
array([0.        , 0.        , 0.        , 1.57079633, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ]), 
array([6.28318531, 6.28318531, 6.28318531, 3.14159265, 6.28318531,
       6.28318531, 6.28318531, 6.28318531, 6.28318531, 6.28318531,
       3.14159265, 6.28318531])

In [ ]:
(array([0.        , 0.        , 0.        , 1.57079633,
        0.        , 0.        , 0.        , 0.        , 
        0.        , 0.        , 0.        , 0.        ]), 
array([6.28318531, 6.28318531, 6.28318531, 3.14159265, 
       6.28318531, 6.28318531, 6.28318531, 6.28318531, 
       6.28318531, 6.28318531, 3.14159265, 6.28318531])))

In [5]:
a = np.angle(np.matmul(H.conj().T, w_opt))
a[a<0] += 2*np.pi

In [6]:
[2.06843940e-17 3.80416698e+00 5.52578675e+00 2.28833435e+00
 4.90874455e-01 4.87426410e+00 5.46282896e+00 5.67190191e+00
 5.78971549e+00 5.23022332e+00 5.48339464e+00 5.23491182e+00]
a

array([2.06843940e-17, 3.80416698e+00, 5.52578675e+00, 2.28833435e+00,
       4.90874455e-01, 4.87426410e+00, 5.46282896e+00, 5.67190191e+00,
       5.78971549e+00, 5.23022332e+00, 5.48339464e+00, 5.23491182e+00])

In [7]:
solve_bb(instance, max_ant=3)

timestep 0, U 1.0440346782949566, L 1.0879950695796468, len_nodes 1, depth_tree 1
ended
result [1. 0. 1. 1.] 1.0900084094824534


((array([1., 0., 1., 1.]),
  array([0.40771115-0.25052795j, 0.        +0.j        ,
         0.73848564-0.06046874j, 0.50541963-0.23780089j])),
 1.0440346782949566,
 0,
 0.006102085113525391)

## GNN training experiments

In [14]:
from setting import ETA_EXP, NODE_DEPTH_INDEX, TASK, DATA_PATH, MODEL_PATH, RESULT_PATH, LOAD_MODEL, LOAD_MODEL_PATH, CLASS_IMBALANCE_WT, LAMBDA_ETA, DAGGER_NUM_ITER, DAGGER_NUM_TRAIN_EXAMPLES_PER_ITER, DAGGER_NUM_VALID_EXAMPLES_PER_ITER, BB_MAX_STEPS

if TASK == 'antenna_selection':
    from antenna_selection.observation import Observation, LinearObservation
    from antenna_selection.as_bb_test import ASBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_cast_beamforming':
    from single_beamforming.observation import Observation, LinearObservation
    from single_beamforming.acr_bb import ACRBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_group_as_bm':
    from single_group_as_bm.observation import Observation, LinearObservation
    from single_group_as_bm.bb import BBenv as Environment, DefaultBranchingPolicy, solve_bb

import torch
import torch.nn as nn
import numpy as np

from gnn_policy import GNNPolicy, GNNNodeSelectionPolicy
from tqdm import tqdm
import torch_geometric
import gzip
import pickle
from gnn_dataset import GraphNodeDataset, instance_generator
from pathlib import Path
from gnn_dataset import get_graph_from_obs
import shutil
import time
import os
import random


from models.fcn_policy import FCNNodeSelectionLinearPolicy, FCNNodeDataset
from torch.utils.data import DataLoader
from dagger_collect_data_multiprocess import DataCollect
import csv
from torch.distributions import Exponential

torch.set_num_threads(1)

np.random.seed(300)
N, M, max_ant = 6, 12, 2 
train_filepath = os.path.join(DATA_PATH, 'N={},M={},L={}/'.format(N,M,max_ant)) 
policy_type = 'gnn'

# train instances should be a list of tuples (H, w_opt) 
NodeDataset = GraphNodeDataset
DataLoader = torch_geometric.data.DataLoader
NodePolicy = GNNNodeSelectionPolicy

# training data is inside policy_data and the oracle solutions are inside oracle_data 
train_filepath = os.path.join(train_filepath, 'policy_data')
valid_filepath = os.path.join(train_filepath, 'valid_policy_data')


instances = instance_generator(M, N)

# Parameters for training
DEVICE = 'cuda'
learning_rate = 0.001
train_epochs = 10
policy = NodePolicy()
policy = policy.to(DEVICE)
optimizer = torch.optim.Adam(policy.parameters(), lr=learning_rate)

model_folderpath = os.path.join(MODEL_PATH, 'gnn_exp')

if not os.path.isdir(model_folderpath):
    Path(model_folderpath).mkdir(exist_ok = True)

train_loss = 0
valid_loss = 0
train_acc = 0
valid_acc = 0
train_fpr = 0
train_fnr = 0
valid_fpr = 0
valid_fnr = 0

model_filepath = os.path.join(model_folderpath, 'gnn_exp.model')
torch.save(policy.eval().to('cpu').state_dict(), model_filepath)

train_files = [str(path) for path in Path(train_filepath).glob('sample_*.pkl')]            
# valid_files = [str(path) for path in Path(valid_filepath).glob('sample_*.pkl')]
random.shuffle(train_files)
valid_files = train_files[int(0.8*len(train_files)):]
train_files = train_files[:int(0.8*len(train_files))]

train_data = NodeDataset(train_files)
train_loader = DataLoader(train_data, batch_size=128, shuffle=True)

valid_data = NodeDataset(valid_files)
valid_loader = DataLoader(valid_data, batch_size=128, shuffle=True)

policy = policy.train().to(DEVICE)

def np_loss(output, target, lmb):
    return sum(target*(1-output) + lmb*(1-target)*(output))

# training stage
total_data = 0
for _ in tqdm(range(train_epochs)):
    mean_loss = 0
    mean_acc = 0
    n_samples_processed = 0
    targets_list = torch.Tensor([]).to(DEVICE)
    preds_list = torch.Tensor([]).to(DEVICE)
    for batch_data in (train_loader):
        batch, target = batch_data
        batch = batch.to(DEVICE)
        target = target.to(DEVICE)*1

        if policy_type == 'gnn':
            batch_size = batch.num_graphs
            num_vars = int(batch.variable_features.shape[0]/batch_size)
            wts = torch.tensor([batch.variable_features[i*num_vars, NODE_DEPTH_INDEX] for i in range(batch_size)], dtype=torch.float32)
        else:
            batch_size = batch.shape[0] 
            wts = batch[:,-25]

        wts = 3/wts
        wts = wts.to(DEVICE)

        # print([batch.variable_features[i*num_vars, 9].item() for i in range(batch_size)], wts, target)
        wts = ((target)*CLASS_IMBALANCE_WT + 1)*wts                   
        out = policy(batch, batch_size)
        bce = nn.BCELoss(weight=wts)   

        try:
            F_w = bce(out.squeeze(), target.to(torch.float).squeeze())
        except:
            F_w = bce(out, target.to(torch.float))

        F_w = np_loss(out.squeeze(), target.to(torch.float).squeeze(), 0.01)
            
        loss = F_w 

        if optimizer is not None:
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        predicted_bestindex = (out>0.5)*1
        accuracy = sum(predicted_bestindex.reshape(-1) == target)

        targets_list = torch.cat((targets_list, target))
        preds_list = torch.cat((preds_list, predicted_bestindex))

        mean_loss += loss.item() * batch_size
        mean_acc += float(accuracy)
        n_samples_processed += batch_size
    total_data = n_samples_processed
    stacked = torch.stack((targets_list, preds_list.squeeze()), dim=1).to(torch.int)
    cmt = torch.zeros(2,2,dtype=torch.int64)
    for p in stacked:
        tl, pl = p.tolist()
        cmt[tl, pl] = cmt[tl, pl] + 1
    print(cmt)
    precision = cmt[1,1]/(cmt[0,1]+cmt[1,1])
    recall = cmt[1,1]/(cmt[1,0]+cmt[1,1])

    train_fpr = cmt[0,1]/(cmt[0,0] + cmt[0,1])
    train_fnr = cmt[1,0]/(cmt[1,0] + cmt[1,1])

    mean_acc = 2* (precision*recall)/(precision+recall)
    mean_loss /= n_samples_processed
    print("Train: precision:{}, recall:{}, f1-score:{}, loss: {}, acc: {}".format(precision, recall, mean_acc, mean_loss, mean_acc))
train_loss = mean_loss
train_acc = mean_acc

valid_mean_loss = 0
valid_mean_acc = 0
n_samples_processed = 0
targets_list = torch.Tensor([]).to(DEVICE)
preds_list = torch.Tensor([]).to(DEVICE)
for batch_data in (valid_loader):
    batch, target = batch_data
    batch = batch.to(DEVICE)
    target = target.to(DEVICE)*1

    if policy_type == 'gnn':
        batch_size = batch.num_graphs
        num_vars = int(batch.variable_features.shape[0]/batch_size)
        wts = torch.tensor([batch.variable_features[i*num_vars, NODE_DEPTH_INDEX] for i in range(batch_size)], dtype=torch.float32)
    else:
        batch_size = batch.shape[0] 
        wts = batch[:,-25]

    wts = 3/wts
    wts = wts.to(DEVICE)

    wts = ((target)*CLASS_IMBALANCE_WT + 1)*wts                   
    out = policy(batch, batch_size)
    bce = nn.BCELoss(weight=wts)   

    try:
        F_w = bce(out.squeeze(), target.to(torch.float).squeeze())
    except:
        F_w = bce(out, target.to(torch.float))

    predicted_bestindex = (out>0.5)*1
    accuracy = sum(predicted_bestindex.reshape(-1) == target)

    targets_list = torch.cat((targets_list, target))
    preds_list = torch.cat((preds_list, predicted_bestindex))

    valid_mean_loss += loss.item() * batch_size
    valid_mean_acc += float(accuracy)
    n_samples_processed += batch_size
total_data = n_samples_processed
stacked = torch.stack((targets_list, preds_list.squeeze()), dim=1).to(torch.int)
cmt = torch.zeros(2,2,dtype=torch.int64)
for p in stacked:
    tl, pl = p.tolist()
    cmt[tl, pl] = cmt[tl, pl] + 1
print(cmt)
precision = cmt[1,1]/(cmt[0,1]+cmt[1,1])
recall = cmt[1,1]/(cmt[1,0]+cmt[1,1])

valid_fpr = cmt[0,1]/(cmt[0,0] + cmt[0,1])
valid_fnr = cmt[1,0]/(cmt[1,0] + cmt[1,1])

valid_mean_acc = 2* (precision*recall)/(precision+recall)
valid_mean_loss /= n_samples_processed

valid_loss = mean_loss
valid_acc = mean_acc

print("Valid: precision:{}, recall:{}, f1-score:{}, loss: {}, acc: {}".format(precision, recall, valid_mean_acc, valid_mean_loss, valid_acc))


 10%|█         | 1/10 [00:02<00:22,  2.45s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.4237483987808228, acc: 0.15855786204338074


 20%|██        | 2/10 [00:04<00:19,  2.48s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.166904507169598, acc: 0.15855786204338074


 30%|███       | 3/10 [00:07<00:17,  2.49s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1666645074204394, acc: 0.15855786204338074


 40%|████      | 4/10 [00:09<00:14,  2.37s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1673845066679152, acc: 0.15855786204338074


 50%|█████     | 5/10 [00:11<00:11,  2.34s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1664245076932405, acc: 0.15855786204338074


 60%|██████    | 6/10 [00:14<00:09,  2.30s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1666645074204394, acc: 0.15855786204338074


 70%|███████   | 7/10 [00:16<00:07,  2.34s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1664245076932405, acc: 0.15855786204338074


 80%|████████  | 8/10 [00:18<00:04,  2.36s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.166904507169598, acc: 0.15855786204338074


 90%|█████████ | 9/10 [00:21<00:02,  2.31s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1666645074204394, acc: 0.15855786204338074


100%|██████████| 10/10 [00:23<00:00,  2.36s/it]

tensor([[   0, 4341],
        [   0,  409]])
Train: precision:0.08610526472330093, recall:1.0, f1-score:0.15855786204338074, loss: 1.1666645074204394, acc: 0.15855786204338074


tensor([[   0, 1088],
        [   0,  100]])
Valid: precision:0.08417508751153946, recall:1.0, f1-score:0.1552795022726059, loss: 0.12999998033046722, acc: 0.15855786204338074


In [ ]:
from setting import ETA_EXP, NODE_DEPTH_INDEX, TASK, DATA_PATH, MODEL_PATH, RESULT_PATH, LOAD_MODEL, LOAD_MODEL_PATH, CLASS_IMBALANCE_WT, LAMBDA_ETA, DAGGER_NUM_ITER, DAGGER_NUM_TRAIN_EXAMPLES_PER_ITER, DAGGER_NUM_VALID_EXAMPLES_PER_ITER, BB_MAX_STEPS

if TASK == 'antenna_selection':
    from antenna_selection.observation import Observation, LinearObservation
    from antenna_selection.as_bb_test import ASBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_cast_beamforming':
    from single_beamforming.observation import Observation, LinearObservation
    from single_beamforming.acr_bb import ACRBBenv as Environment, DefaultBranchingPolicy, solve_bb

elif TASK == 'single_group_as_bm':
    from single_group_as_bm.observation import Observation, LinearObservation
    from single_group_as_bm.bb import BBenv as Environment, DefaultBranchingPolicy, solve_bb

import torch
import torch.nn as nn
import numpy as np

from gnn_policy import GNNPolicy, GNNNodeSelectionPolicy
from tqdm import tqdm
import torch_geometric
import gzip
import pickle
from gnn_dataset import GraphNodeDataset, instance_generator
from pathlib import Path
from gnn_dataset import get_graph_from_obs
import shutil
import time
import os
import random


from models.fcn_policy import FCNNodeSelectionLinearPolicy, FCNNodeDataset
from torch.utils.data import DataLoader
from dagger_collect_data_multiprocess import DataCollect
import csv
from torch.distributions import Exponential

torch.set_num_threads(1)

np.random.seed(300)
N, M, max_ant = 6, 12, 2 
train_filepath = os.path.join(DATA_PATH, 'N={},M={},L={}/'.format(N,M,max_ant)) 
policy_type = 'gnn'

# train instances should be a list of tuples (H, w_opt) 
NodeDataset = GraphNodeDataset
DataLoader = torch_geometric.data.DataLoader
NodePolicy = GNNNodeSelectionPolicy

# training data is inside policy_data and the oracle solutions are inside oracle_data 
train_filepath = os.path.join(train_filepath, 'policy_data')
valid_filepath = os.path.join(train_filepath, 'valid_policy_data')


instances = instance_generator(M, N)

# Parameters for training
DEVICE = 'cuda'
learning_rate = 0.001
train_epochs = 10
policy = NodePolicy()
policy = policy.to(DEVICE)
optimizer = torch.optim.Adam(policy.parameters(), lr=learning_rate)

model_folderpath = os.path.join(MODEL_PATH, 'gnn_exp')

if not os.path.isdir(model_folderpath):
    Path(model_folderpath).mkdir(exist_ok = True)

train_loss = 0
valid_loss = 0
train_acc = 0
valid_acc = 0
train_fpr = 0
train_fnr = 0
valid_fpr = 0
valid_fnr = 0

model_filepath = os.path.join(model_folderpath, 'gnn_exp.model')
torch.save(policy.eval().to('cpu').state_dict(), model_filepath)

train_files = [str(path) for path in Path(train_filepath).glob('sample_*.pkl')]            
# valid_files = [str(path) for path in Path(valid_filepath).glob('sample_*.pkl')]
random.shuffle(train_files)
valid_files = train_files[int(0.8*len(train_files)):]
train_files = train_files[:int(0.8*len(train_files))]

train_data = NodeDataset(train_files)
train_loader = DataLoader(train_data, batch_size=128, shuffle=True)

valid_data = NodeDataset(valid_files)
valid_loader = DataLoader(valid_data, batch_size=128, shuffle=True)

policy = policy.train().to(DEVICE)

def np_loss(output, target, lmb):
    return sum(target*(1-output) + lmb*(1-target)*(output))

# training stage
total_data = 0
for _ in tqdm(range(train_epochs)):
    mean_loss = 0
    mean_acc = 0
    n_samples_processed = 0
    targets_list = torch.Tensor([]).to(DEVICE)
    preds_list = torch.Tensor([]).to(DEVICE)
    for batch_data in (train_loader):
        batch, target = batch_data
        batch = batch.to(DEVICE)
        target = target.to(DEVICE)*1

        if policy_type == 'gnn':
            batch_size = batch.num_graphs
            num_vars = int(batch.variable_features.shape[0]/batch_size)
            wts = torch.tensor([batch.variable_features[i*num_vars, NODE_DEPTH_INDEX] for i in range(batch_size)], dtype=torch.float32)
        else:
            batch_size = batch.shape[0] 
            wts = batch[:,-25]

        wts = 3/wts
        wts = wts.to(DEVICE)

        # print([batch.variable_features[i*num_vars, 9].item() for i in range(batch_size)], wts, target)
        wts = ((target)*CLASS_IMBALANCE_WT + 1)*wts                   
        out = policy(batch, batch_size)
        bce = nn.BCELoss(weight=wts)   

        try:
            F_w = bce(out.squeeze(), target.to(torch.float).squeeze())
        except:
            F_w = bce(out, target.to(torch.float))

#         F_w = np_loss(out.squeeze(), target.to(torch.float).squeeze(), 0.1)
            
        loss = F_w 

        if optimizer is not None:
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        predicted_bestindex = (out>0.5)*1
        accuracy = sum(predicted_bestindex.reshape(-1) == target)

        targets_list = torch.cat((targets_list, target))
        preds_list = torch.cat((preds_list, predicted_bestindex))

        mean_loss += loss.item() * batch_size
        mean_acc += float(accuracy)
        n_samples_processed += batch_size
    total_data = n_samples_processed
    stacked = torch.stack((targets_list, preds_list.squeeze()), dim=1).to(torch.int)
    cmt = torch.zeros(2,2,dtype=torch.int64)
    for p in stacked:
        tl, pl = p.tolist()
        cmt[tl, pl] = cmt[tl, pl] + 1
    print(cmt)
    precision = cmt[1,1]/(cmt[0,1]+cmt[1,1])
    recall = cmt[1,1]/(cmt[1,0]+cmt[1,1])

    train_fpr = cmt[0,1]/(cmt[0,0] + cmt[0,1])
    train_fnr = cmt[1,0]/(cmt[1,0] + cmt[1,1])

    mean_acc = 2* (precision*recall)/(precision+recall)
    mean_loss /= n_samples_processed
    print("Train: precision:{}, recall:{}, f1-score:{}, loss: {}, acc: {}".format(precision, recall, mean_acc, mean_loss, mean_acc))
train_loss = mean_loss
train_acc = mean_acc

valid_mean_loss = 0
valid_mean_acc = 0
n_samples_processed = 0
targets_list = torch.Tensor([]).to(DEVICE)
preds_list = torch.Tensor([]).to(DEVICE)
for batch_data in (valid_loader):
    batch, target = batch_data
    batch = batch.to(DEVICE)
    target = target.to(DEVICE)*1

    if policy_type == 'gnn':
        batch_size = batch.num_graphs
        num_vars = int(batch.variable_features.shape[0]/batch_size)
        wts = torch.tensor([batch.variable_features[i*num_vars, NODE_DEPTH_INDEX] for i in range(batch_size)], dtype=torch.float32)
    else:
        batch_size = batch.shape[0] 
        wts = batch[:,-25]

    wts = 3/wts
    wts = wts.to(DEVICE)

    wts = ((target)*CLASS_IMBALANCE_WT + 1)*wts                   
    out = policy(batch, batch_size)
    bce = nn.BCELoss(weight=wts)   

    try:
        F_w = bce(out.squeeze(), target.to(torch.float).squeeze())
    except:
        F_w = bce(out, target.to(torch.float))

    predicted_bestindex = (out>0.5)*1
    accuracy = sum(predicted_bestindex.reshape(-1) == target)

    targets_list = torch.cat((targets_list, target))
    preds_list = torch.cat((preds_list, predicted_bestindex))

    valid_mean_loss += loss.item() * batch_size
    valid_mean_acc += float(accuracy)
    n_samples_processed += batch_size
total_data = n_samples_processed
stacked = torch.stack((targets_list, preds_list.squeeze()), dim=1).to(torch.int)
cmt = torch.zeros(2,2,dtype=torch.int64)
for p in stacked:
    tl, pl = p.tolist()
    cmt[tl, pl] = cmt[tl, pl] + 1
print(cmt)
precision = cmt[1,1]/(cmt[0,1]+cmt[1,1])
recall = cmt[1,1]/(cmt[1,0]+cmt[1,1])

valid_fpr = cmt[0,1]/(cmt[0,0] + cmt[0,1])
valid_fnr = cmt[1,0]/(cmt[1,0] + cmt[1,1])

valid_mean_acc = 2* (precision*recall)/(precision+recall)
valid_mean_loss /= n_samples_processed

valid_loss = mean_loss
valid_acc = mean_acc

print("Valid: precision:{}, recall:{}, f1-score:{}, loss: {}, acc: {}".format(precision, recall, valid_mean_acc, valid_mean_loss, valid_acc))


In [9]:
import random

random.shuffle(train_files)
valid_files = train_files[int(0.8*len(train_files)):]
train_files = train_files[:int(0.8*len(train_files))]

In [10]:
len(valid_files)

1188

In [11]:
len(train_files)

4750